# FIXED
BRTOS/event.obj: ../BRTOS/event.c
BRTOS/event.obj: ../BRTOS/includes/event.h
BRTOS/event.obj: ../BRTOS/includes/OS_types.h
BRTOS/event.obj: ../BRTOS/includes/BRTOS.h
BRTOS/event.obj: ../BRTOS/includes/../HAL/HAL.h
BRTOS/event.obj: ../BRTOS/includes/../HAL/hardware.h
BRTOS/event.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/msp430f2274.h
BRTOS/event.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/in430.h
BRTOS/event.obj: ../BRTOS/includes/event.h
BRTOS/event.obj: ../BRTOS/includes/queue.h
BRTOS/event.obj: ../BRTOS/includes/drivers.h
BRTOS/event.obj: ../BRTOS/includes/../includes/BRTOS.h
BRTOS/event.obj: ../BRTOS/includes/tasks.h
BRTOS/event.obj: ../BRTOS/includes/debug_stack.h
BRTOS/event.obj: ../BRTOS/includes/OS_RTC.h
BRTOS/event.obj: ../BRTOS/includes/debug_stack.h
BRTOS/event.obj: D:/CODE_COMPOSER/ccsv4/tools/compiler/msp430/include/stdlib.h
BRTOS/event.obj: D:/CODE_COMPOSER/ccsv4/tools/compiler/msp430/include/linkage.h
