# FIXED
BRTOS/debug_stack.obj: ../BRTOS/debug_stack.c
BRTOS/debug_stack.obj: ../BRTOS/includes/BRTOS.h
BRTOS/debug_stack.obj: ../BRTOS/includes/../HAL/HAL.h
BRTOS/debug_stack.obj: ../BRTOS/includes/../HAL/../includes/OS_types.h
BRTOS/debug_stack.obj: ../BRTOS/includes/../HAL/hardware.h
BRTOS/debug_stack.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/msp430f2274.h
BRTOS/debug_stack.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/in430.h
BRTOS/debug_stack.obj: ../BRTOS/includes/event.h
BRTOS/debug_stack.obj: ../BRTOS/includes/BRTOS.h
BRTOS/debug_stack.obj: ../BRTOS/includes/queue.h
BRTOS/debug_stack.obj: ../BRTOS/includes/drivers.h
BRTOS/debug_stack.obj: ../BRTOS/includes/tasks.h
BRTOS/debug_stack.obj: ../BRTOS/includes/debug_stack.h
BRTOS/debug_stack.obj: ../BRTOS/includes/OS_RTC.h
BRTOS/debug_stack.obj: ../BRTOS/includes/debug_stack.h
