# FIXED
main.obj: ../main.c
main.obj: ../BRTOS/includes/BRTOS.h
main.obj: ../BRTOS/includes/../HAL/HAL.h
main.obj: ../BRTOS/includes/../HAL/../includes/OS_types.h
main.obj: ../BRTOS/includes/../HAL/hardware.h
main.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/msp430f2274.h
main.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/in430.h
main.obj: ../BRTOS/includes/event.h
main.obj: ../BRTOS/includes/BRTOS.h
main.obj: ../BRTOS/includes/queue.h
main.obj: ../BRTOS/includes/drivers.h
main.obj: ../BRTOS/includes/tasks.h
main.obj: ../BRTOS/includes/debug_stack.h
main.obj: ../BRTOS/includes/OS_RTC.h
main.obj: ../BRTOS/includes/debug_stack.h
main.obj: ../BRTOS/includes/mcu_init.h
