# FIXED
tasks.obj: ../tasks.c
tasks.obj: ../BRTOS/includes/BRTOS.h
tasks.obj: ../BRTOS/includes/../HAL/HAL.h
tasks.obj: ../BRTOS/includes/../HAL/../includes/OS_types.h
tasks.obj: ../BRTOS/includes/../HAL/hardware.h
tasks.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/msp430f2274.h
tasks.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/in430.h
tasks.obj: ../BRTOS/includes/event.h
tasks.obj: ../BRTOS/includes/BRTOS.h
tasks.obj: ../BRTOS/includes/queue.h
tasks.obj: ../BRTOS/includes/drivers.h
tasks.obj: ../BRTOS/includes/tasks.h
tasks.obj: ../BRTOS/includes/debug_stack.h
tasks.obj: ../BRTOS/includes/OS_RTC.h
tasks.obj: ../BRTOS/includes/debug_stack.h
