# FIXED
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/HAL.c
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/BRTOS.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/../HAL/HAL.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/../HAL/../includes/OS_types.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/../HAL/hardware.h
BRTOS/HAL/HAL.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/msp430f2274.h
BRTOS/HAL/HAL.obj: D:/CODE_COMPOSER/ccsv4/msp430/include/in430.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/event.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/BRTOS.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/queue.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/drivers.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/tasks.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/debug_stack.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/OS_RTC.h
BRTOS/HAL/HAL.obj: ../BRTOS/HAL/../includes/debug_stack.h
